### ISSUE TITLE
It looks like you renamed your config.json to config_sample.json?

### ISSUE THREAD

**Issue by Niemetz** [awslabs/lambda-ecs-worker-pattern#12]
Hi Constantin!
  Your js code is trying to read:
  var config = JSON.parse(fs.readFileSync('**config.json**', 'utf8'));
  But your filename is **config_sample.json**.  Am I correct?
  Thanks
  John Nguyen

**Comment by glez-aws** [comment]
Hi John,

thanks for checking out this code example!

Please let me note that this is an old example: Today, nearly 5 years later, there are much better ways of reaching the same goals, including using services like AWS Fargate for running Docker Containers without the need to operate an ECS cluster, using Serverless Application Model (SAM) or Cloud Development Kit (CDK) instead of Fabric for deployment and more.

However, to answer your question: The file config_sample.json ist just there to illustrate how the config file looks like that the Lambda function will use. The real config file remains config.json, but it is generated at deployment time by the fabfile.py Python script, hence it is not visible as a file in Github.

Hope this helps,
   Constantin

**Comment by Niemetz** [comment]
Hi Constantin  Thank you for your quick feedback.  Yes I realized the code is 5 yrs old :-), but I really want to o learn how you did it... old way. :-).  AWS has evolved quite a lot in the last 5 years for sure.   Also thank for the tip on the "config.json" file.  I also just asked you another question on your GitHub.  The question is on the config.py you have this line: SSH_KEY_NAME = 'your-ssh-key.pem'  # Expected to be in ~/.ssh.  Is the SSH key pem is of Docker or AWS secrete access key?  Since I'm new to AWS I won't be able to use the new AWS services that you mentioned because I do not know them well.... I'll be continuing to learn the "hard way" first.  Please help walk me through this.  Thanks  John Nguyen
    On Wednesday, February 12, 2020, 11:37:52 AM EST, Constantin Gonzalez <notifications@github.com> wrote:  
 
 
Hi John,

thanks for checking out this code example!

Please let me note that this is an old example: Today, nearly 5 years later, there are much better ways of reaching the same goals, including using services like AWS Fargate for running Docker Containers without the need to operate an ECS cluster, using Serverless Application Model (SAM) or Cloud Development Kit (CDK) instead of Fabric for deployment and more.

However, to answer your question: The file config_sample.json ist just there to illustrate how the config file looks like that the Lambda function will use. The real config file remains config.json, but it is generated at deployment time by the fabfile.py Python script, hence it is not visible as a file in Github.

Hope this helps,
Constantin

**Comment by glez-aws** [comment]
Hi John,
(see my other comment about the SSH key, the short version is that it's for the ECS cluster.)

glad to see you getting a learning experience out of this. Yes, I agree that learning stuff from the ground up is the best way, even if it takes longer, so I guess you're on the right track!

Feel free to check out AWS videos on YouTube (especially those from AWS re:Invent) as well as blog posts from https://aws.amazon.com/blogs/

Thanks,
   Constantin

**Comment by glez-aws** [comment]
Closing as this seems to be resolved now. Feel free to reopen if anything is missing.
