### ISSUE TITLE
Which SSH_KEY_NAME?

### ISSUE THREAD

**Issue by Niemetz** [awslabs/lambda-ecs-worker-pattern#13]
Hi Constantin
  In your config.py you have an env var SSH_KEY_NAME.  Is this the SSH private key for Docker Registry or  it is for AWS SSH?
  Also in the same file you have two env vars AWS_REGION and AWS_PROFILE.  What is the reason I need to spicy both while the AWS_PROFILE already contains the REGION?
  Thanks
  John Nguyen

**Comment by glez-aws** [comment]
Hi John,

the SSH_KEY_NAME is your EC2 SSH Key for logging into your ECS Cluster so the script can build the Docker image.

Again, this is 5 year old example, and today, I would advise to use a more modern approach: Today, I would use Amazon ECR to store the Docker images because it is easier to integrate. Similary, I would propose to use AWS Code Build in order to build Docker images, instead of logging into an EC2 ECS Cluster over SSH. You can find out more here:

https://aws.amazon.com/ecr/
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html

Hope this helps,
   Constantin

**Comment by Niemetz** [comment]
ic... thanks again... please ignore my last note thenAnd thanks for the tips of ECR and CodeBuild.  I'll take a look at them.J.N
    On Wednesday, February 12, 2020, 11:46:30 AM EST, Constantin Gonzalez <notifications@github.com> wrote:  
 
 
Hi John,

the SSH_KEY_NAME is your EC2 SSH Key for logging into your ECS Cluster so the script can build the Docker image.

Again, this is 5 year old example, and today, I would advise to use a more modern approach: Today, I would use Amazon ECR to store the Docker images because it is easier to integrate. Similary, I would propose to use AWS Code Build in order to build Docker images, instead of logging into an EC2 ECS Cluster over SSH. You can find out more here:

https://aws.amazon.com/ecr/
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html

Hope this helps,
Constantin

**Comment by glez-aws** [comment]
Closing as this seems resolved now. Feel free to reopen otherwise.
